### PR TITLE
Update to monaco-languageclient 8.4.0 and monaco-editor-wrapper 5.1.1

### PR DESCRIPTION
**Pull request by kaisalmen**
In addition to update `monaco-languageclient@8.4.0` this also introduces `monaco-editor-wrapper@5.1.1`:

The wrapper takes a `UserConfig` that configures the language client and monaco-editor and all required `monaco-vscode-api` related services. I switch to vscode textmate cpp highlighting and thereby removes the need for the extra theme definitions.
Also the language client configuration moved into one function that is now included in `editor.ts`.
`monaco-editor-wrapper` internally uses `LanguageClientWrapper` that configures , starts and disposes the languageclient. By using it for the need for more boiler-plate code is removed.

### CODE REVIEW

**Comment by kaisalmen** [comment]
@Guyutongxue the vite build is broken. Using the dev server was no problem. I can reproduce this locally when using:
```shell
npx statikk --port 8000 --coi
```
in the dist folder. I need to find out why

**Comment by guyutongxue** [comment]
Oops.

PR has been reverted and you can recreate one PR once fixing is done.

Btw I should use Vercel to preview PR but I do not have time for now lol

**Comment by kaisalmen** [comment]
@Guyutongxue sorry for the inconvenience. I didn't realize you deploy immediately. I will understand what is wrong. `vite preview` shows the same effect. I will open another PR once this is resolved. Did you test this locally already in dev mode?

**Comment by guyutongxue** [comment]
No, I don't have my 'PC for developing' with me now so, emm I'm just pressing "merge" button on my mobile 🤣

next time I'll test locally first sry

**Pull request merged**
